import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
	{
		_id: uuid(),
		firstName: "Adarsh",
		lastName: "Balika",
		username: "adarshbalika",
		password: "adarshBalika123",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		_id: uuid(),
		firstName: "Aman",
		lastName: "Antil",
		username: "aman3113",
		password: "aman123",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},

	{
		id: uuid(),
		title: "ms",
		firstName: "Sara",
		lastName: "Andersen",
		username: "sara_here",
		password: "sara123",
		picture: "https://randomuser.me/api/portraits/women/58.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "miss",
		firstName: "Edita",
		lastName: "Vestering",
		username: "edita_here",
		password: "edita123",
		picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "ms",
		firstName: "Adina",
		lastName: "Barbosa",
		username: "adinaishere",
		password: "adina123",
		picture: "https://randomuser.me/api/portraits/med/women/28.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Roberto",
		lastName: "Vega",
		username: "veda_roberto",
		password: "vega123",
		picture: "https://randomuser.me/api/portraits/med/men/25.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Rudi",
		lastName: "Droste",
		username: "rudi_is_here",
		password: "rudi123",
		picture: "https://randomuser.me/api/portraits/med/men/83.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mrs",
		firstName: "Carolina",
		lastName: "Lima",
		username: "lima.me",
		password: "lima123",
		picture: "https://randomuser.me/api/portraits/med/women/5.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Emre",
		lastName: "Asikoglu",
		username: "theemre3113",
		password: "emre123",
		picture: "https://randomuser.me/api/portraits/med/men/23.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Kent",
		lastName: "Brewer",
		username: "your_boy_kent",
		password: "kent123",
		picture: "https://randomuser.me/api/portraits/med/men/52.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Evan",
		lastName: "Carlson",
		username: "evan_DJ",
		password: "evan123",
		picture: "https://randomuser.me/api/portraits/med/men/80.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Friedrich-Karl",
		lastName: "Brand",
		username: "brand_boy",
		password: "karl123",
		picture: "https://randomuser.me/api/portraits/med/men/7.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Valentin",
		lastName: "Ortega",
		username: "valentine_gal",
		password: "ortega123",
		picture: "https://randomuser.me/api/portraits/med/men/3.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mrs",
		firstName: "Sibylle",
		lastName: "Leibold",
		username: "sibylle_here",
		password: "leibold123",
		picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mrs",
		firstName: "Elisa",
		lastName: "Lorenzo",
		username: "elisa_here",
		password: "elisa123",
		picture: "https://randomuser.me/api/portraits/med/women/89.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Leevi",
		lastName: "Savela",
		username: "leevi_your_gal",
		password: "ssavela123",
		picture: "https://randomuser.me/api/portraits/med/men/67.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mrs",
		firstName: "Karoline",
		lastName: "Sviggum",
		username: "karoLINE",
		password: "kar123",
		picture: "https://randomuser.me/api/portraits/med/women/61.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "ms",
		firstName: "Nuria",
		lastName: "Leon",
		username: "nuria_here",
		password: "leon123",
		picture: "https://randomuser.me/api/portraits/med/women/93.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Lance",
		lastName: "Foster",
		username: "lance_the_Foster",
		password: "lance123",
		picture: "https://randomuser.me/api/portraits/med/men/13.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "miss",
		firstName: "Naomi",
		lastName: "Rodrigues",
		username: "naomi_love",
		password: "naomi123",
		picture: "https://randomuser.me/api/portraits/med/women/39.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Evan",
		lastName: "Roux",
		username: "evan_bouy",
		password: "roux123",
		picture: "https://randomuser.me/api/portraits/med/men/59.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
	{
		id: uuid(),
		title: "mr",
		firstName: "Miguel",
		lastName: "Lima",
		username: "miguel3211",
		password: "lima123",
		picture: "https://randomuser.me/api/portraits/med/men/31.jpg",
		createdAt: formatDate(),
		updatedAt: formatDate(),
	},
];
